## NumPy는 Numerical Python 의 줄임말

> NumPy 제공 기능
- 빠르고 메모리를 효율적으로 사용하며 벡터 산술연산과 세련된 브로드캐스팅 기능을 제공하는 다차원 배열인 ndarray
- 반복문을 작성할 필요 없이 전체 데이터 배열에 대해 빠른 연산을 제공하는 표준 수학함수
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 올려진 파일을 사용하는 도구
- 선형대수, 난수발생기, 푸리에 변환 기능
- C, C++, FORTRAN으로 쓰여진 코드를 통합하는 도구

In [1]:
from numpy.random import randn
import numpy as np

In [2]:
# 그래프를 바로 보기 위한 명령어
%matplotlib inline

## 1. The NumPy ndarray: a multidimensional array object

> 다차원 배열 객체

In [3]:
data = randn(2,3)
data

array([[ 0.55197673, -0.65019552, -0.33958787],
       [ 1.63514931,  2.40794109,  0.61785189]])

2행 3열의 난수를 지닌 array 출력.

In [4]:
data * 10

array([[ 5.51976729, -6.50195518, -3.39587866],
       [16.35149305, 24.07941092,  6.17851893]])

In [5]:
data + data

array([[ 1.10395346, -1.30039104, -0.67917573],
       [ 3.27029861,  4.81588218,  1.23570379]])

스칼라 형태와 벡터 형태 2가지의 데이터 형태가 있는데,
위와 같이 단순히 처리되는 것들을 스칼라 형태이다.
파이썬은 스칼라와 벡터 두 형태 모두를 지원한다.

In [6]:
data

array([[ 0.55197673, -0.65019552, -0.33958787],
       [ 1.63514931,  2.40794109,  0.61785189]])

In [7]:
data.shape

(2, 3)

구조가 2차원으로 되어있다는 의미 첫번째가 행, 두번재가 열

In [8]:
data.dtype

dtype('float64')

### Creating ndarrays

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

ndim은 차수를 나타내는 것이다. 2차원이므로 2가 출력/
 [] 개수에 따라 차원 추가된다. 

In [14]:
arr2.shape

(2, 4)

In [15]:
arr1.dtype

dtype('float64')

In [16]:
arr2.dtype

dtype('int32')

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2,3,2))

array([[[2.5e-322, 0.0e+000],
        [0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000]],

       [[0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000]]])

In [27]:
x = np.empty((2,3,2))
x.ndim

3

np.empty는 뒤의 숫자부터 해석해야 한다.
- 2개의 난수를 가진
- 3개의 리스트를
- 2개의 묶음으로 만드는 것

[Tip] np.empty 
np.empty는 0으로 초기화된 배열을 반환하지 않는다. 
대부분 empty는 초기화되지 않은 값으로 채워진 배열을 반환한다.

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [31]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1.dtype


dtype('float64')

In [32]:
arr2 = np.array([1,2,3], dtype=np.int32)
arr2.dtype

dtype('int32')

int는 32비트 flat는 64비트

In [33]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [34]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

Tip] astype 
astype을 호출하면 새로운 dtype이 이전 dtype과 같아도 항상 새로운 배열을 생성(데이터를 복사)한다. 
float64나 float32 같은 부동소수점은 근사값이라는 사실을 염두에 두는게 중요하다.

In [36]:
# astype 을 사용하여 숫자로 변환
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [37]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [38]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [40]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
# u4 는 unit32 와 동일
empty_unit32 = np.empty(8, dtype='u4')
empty_unit32

array([  43450508,          0,       4466,    1733120,  359792640,
       2835349504,    2388480, 1224343552], dtype=uint32)

### Operations between arrays and scalars
> 배열과 스칼라간의 연산

In [47]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [48]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [49]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [51]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### Basic indexing and slicing
> 색인과 슬라이싱 기초

> 이 부분이 중요함.

In [53]:
arr = np.arange(10)
arr
# arr[5]
# arr[5:8]
# arr[5:8] =12

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr[5]

5

In [55]:
arr[5:8]

array([5, 6, 7])

In [56]:
arr[5:8] =12

In [57]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [58]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [60]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [61]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

[Tip] 슬라이스 복사본 
만약에 뷰 대신 ndarray 슬라이스의 복사본을 얻고 싶다면 arr[5:8].copy()를 사용해서 명시적으로 배열을 복사하면 된다.



### 2차원 배열

In [62]:
# NumPy 배열에서 요소 색인하기
# reference(Figure4_1, 600)

\# 주의!!! axis는 축이라는 의미를 지니고 있는 단어이지만, NumPy 사용 시 사실상 차원의 의미로 이해해야 한다. 최초 작성자가 영어가 부족해서 생긴 해프닝임.

In [65]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [66]:
arr2d[0][2]

3

In [67]:
arr2d[0, 2]

3

### 3차원 배열

In [68]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
arr3d[1,0]

array([7, 8, 9])

### Indexing with slices
> 슬라이스 색인

In [74]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [75]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [76]:
# 2차원 배열 슬라이싱
# reference(Figure4_2, 600)

In [77]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [80]:
arr2d[1,:2]

array([4, 5])

In [82]:
arr2d[2,:1]

array([7])

In [83]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [84]:
arr2d[:2,1:] = 0

In [85]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean indexing
> 불리언 색인
- boolean은 참, 거짓으로 나누는 것

In [86]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [88]:
data = randn(7, 4)
data

array([[-0.41101669, -0.00794451, -0.73005248,  0.43916166],
       [-0.69334305, -1.84510945,  0.75148255, -0.83824814],
       [ 0.36539611, -1.64814547, -0.56153809, -1.08152753],
       [-0.02084075, -0.82018218, -0.10088511,  0.81020565],
       [ 0.02443026, -0.40714746, -0.59542112,  0.00294556],
       [-1.02498354, -0.25717349, -0.28127227, -0.55176824],
       [-0.49917208, -1.61067466,  0.54389752, -0.68820224]])

In [89]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [90]:
data[names == 'Bob']

array([[-0.41101669, -0.00794451, -0.73005248,  0.43916166],
       [-0.02084075, -0.82018218, -0.10088511,  0.81020565]])

In [91]:
data[names == 'Bob', 2:]

array([[-0.73005248,  0.43916166],
       [-0.10088511,  0.81020565]])

In [92]:
data[names == 'Bob', 3]

array([0.43916166, 0.81020565])

In [93]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [94]:
data[-(names == 'Bob')]

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

[Tip] NumPy Boolean Negative 
'-' 연산자는 사용하지 않으며, ~ 혹은 Logical Not 함수를 대신 사용한다.

In [95]:
data[~(names == 'Bob')]

array([[-0.69334305, -1.84510945,  0.75148255, -0.83824814],
       [ 0.36539611, -1.64814547, -0.56153809, -1.08152753],
       [ 0.02443026, -0.40714746, -0.59542112,  0.00294556],
       [-1.02498354, -0.25717349, -0.28127227, -0.55176824],
       [-0.49917208, -1.61067466,  0.54389752, -0.68820224]])

In [96]:
data[ (names != 'Bob')]

array([[-0.69334305, -1.84510945,  0.75148255, -0.83824814],
       [ 0.36539611, -1.64814547, -0.56153809, -1.08152753],
       [ 0.02443026, -0.40714746, -0.59542112,  0.00294556],
       [-1.02498354, -0.25717349, -0.28127227, -0.55176824],
       [-0.49917208, -1.61067466,  0.54389752, -0.68820224]])

In [97]:
data

array([[-0.41101669, -0.00794451, -0.73005248,  0.43916166],
       [-0.69334305, -1.84510945,  0.75148255, -0.83824814],
       [ 0.36539611, -1.64814547, -0.56153809, -1.08152753],
       [-0.02084075, -0.82018218, -0.10088511,  0.81020565],
       [ 0.02443026, -0.40714746, -0.59542112,  0.00294556],
       [-1.02498354, -0.25717349, -0.28127227, -0.55176824],
       [-0.49917208, -1.61067466,  0.54389752, -0.68820224]])

In [98]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [99]:
data[mask]

array([[-0.41101669, -0.00794451, -0.73005248,  0.43916166],
       [ 0.36539611, -1.64814547, -0.56153809, -1.08152753],
       [-0.02084075, -0.82018218, -0.10088511,  0.81020565],
       [ 0.02443026, -0.40714746, -0.59542112,  0.00294556]])

In [100]:
data[data < 0] = 0
data

array([[0.        , 0.        , 0.        , 0.43916166],
       [0.        , 0.        , 0.75148255, 0.        ],
       [0.36539611, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.81020565],
       [0.02443026, 0.        , 0.        , 0.00294556],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.54389752, 0.        ]])

In [101]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.75148255, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.54389752, 0.        ]])

### Fancy indexing
> 팬시 색인
- 팬시 색인은 정수 배열을 사용한 색인을 설명하기 위해 NumPy에서 차용한 단어다.

In [103]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

특정한 순서로 로우를 선택하고 싶다면, 그냥 원하는 순서가 명시된 정수가 담긴 ndarray나 리스트를 넘기면 된다

In [104]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [105]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

- 다차원 색인 배열을 넘기는 것은 조금 다르게 동작
- 각각의 색인 튜를에 대응하는 1차원 배열을 선택한 후, reshape 시킨다.

In [106]:
# more on reshape in Chapter 12
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

- (1, 0), (5, 3), (7, 1), (2, 2) 에 대응하는 요소 선택

In [107]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [108]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

- 위의 코드의 경우에는 원하는 열의 순서대로 가져오고 싶을 때 쓰는 방식이다.

In [109]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

- 마찬가지로 원하는 열의 순서대로 가져오는 것을 지원하기 위해 만들어진 함수가 np.ix이다.

### Transposing arrays and swapping axes 
> 배열 전치와 축 바꾸기
- 배열 전치는 데이터를 복사하지 않고 데이터 모양이 바뀐 뷰를 반환하는 특별한 기능
- ndarray는 transpose 메소드와 T라는 이름의 특수한 속성을 가진다.
- 다차원 배열의 경우 transpose 메소드는 튜플로 축 번호를 받아서 치환한다.

In [111]:
? np.dot

In [112]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [114]:
arr.T   # 축들을 바꿔준다. axes0과 axes1을 바꿔준다.

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [115]:
arr = np.random.randn(6, 3)
arr

array([[-1.5292399 ,  0.19436351,  0.50289309],
       [ 0.55116056, -0.76941378,  0.90318594],
       [ 0.58128907,  1.8065226 , -0.24552114],
       [-1.96467012, -0.54856842, -0.75091131],
       [-0.0091926 , -0.32620446, -0.30733579],
       [ 0.2573579 , -1.67384551,  0.50379725]])

In [117]:
np.dot(arr.T, arr)   # 행렬곱을 실행시켜주는 함수.

array([[ 6.90649589,  0.97879017,  1.19381197],
       [ 0.97879017,  7.10239411, -1.37181735],
       [ 1.19381197, -1.37181735,  2.04106169]])

In [118]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [119]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [121]:
? arr.transpose

In [122]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [123]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [124]:
?arr.swapaxes